### ISSUE TITLE
EIA API version 2?

### ISSUE THREAD

**Issue by jameelalsalam** [leonawicz/eia#10]
Is there a plan to update this package to use the EIA API version 2? I am interested in either helping to update this package, or in working on a new package to use the new version of the API. Using the `eia` package has been very helpful to me over the years.

EIA has released a version 2 of its API. My understanding is that while the API v1 is still currently operating, that it could be shut down soon. From the FAQ on their website:
"What exact day is APIv1 shutting down?
We aren't able to provide a specific date at this time, but we will as the date draws closer. For your planning purposes, we are targeting January 2023."

They are providing a backwards-compatibility endpoint which should allow results to be retrieved by series ID through that endpoint. However, I think at least some changes are necessary to use this backwards-compatibility endpoint.
[EIA API documentation](https://www.eia.gov/opendata/documentation.php)

In addition, it seems like they have worked hard to improve the metadata available and structure of the API overall. I am hopeful that there are possibilities in an R package to take advantage of the improvements they have made.

thanks!
Jameel

**Comment by leonawicz** [comment]
Hi Jameel,

I am aware of the new API version but at present do not have the development bandwidth to address this. However, if you, or someone from ROpenSci does, I can review a PR.

It sounds like the low-hanging fruit for now would be to make use of this backwards-compatible endpoint on the new version of the API rather than redesign the entire package at this time.

Regards,
Matt

**Comment by jameelalsalam** [comment]
Okay, I will work on that. As a side note, it looks like at least some of the CI (e.g., travis.org) has been deprecated, so it seems like some changes to the CI will be necessary as well.

**Comment by jameelalsalam** [comment]
Since it has been awhile, I wanted to give an update, There are quite a lot of changes in the EIA version 2 API which will require deprecating number of functions when the version 1 API stops functioning (at least given current features). Because of the extensive changes I found it challenging to work directly on a PR to use the backwards-compatibility endpoint.

I have been working on a rewrite package at: https://github.com/jameelalsalam/eia2. It is getting towards being functional, but is still missing documentation and other features. My plan is to pull out part of the code that I am working on their for a PR to this package to use the backwards-compatibility endpoint.

I have not heard any update on the timing for the version 1 API going away.

**Comment by sawyervillers** [comment]
Hi Jameel - Any luck?  The EIA terminated Version 1.0 of their API and it broke a bunch of different packages.

**Comment by jameelalsalam** [comment]
@sawyervillers There are many changes in the API version 2... I am not sure that my previous plan makes sense any more, particularly now that the v1 API is gone. My rewrite package has progressed decently far along, however, you could try that.

@leonawicz do you still think it makes sense to bring over a function to access the compatibility endpoint to here? It would basically be `eia1_series`, found here: https://github.com/jameelalsalam/eia2/blob/main/R/eia1_series.R

**Comment by leonawicz** [comment]
See issue #13
