### ISSUE TITLE
404 Error when trying to pull series from API

### ISSUE THREAD

**Issue by tanga94** [leonawicz/eia#12]
Hi, I'm trying to update data in a script that I've run in the past and I'm getting the following error. Is there a way to fix this/does this package still function? The last time I ran it (2 months ago) it was working perfectly.

```
library(eia)
eia_set_key('7eba73584cfb231e1c6ee0282ff8f2a8')

eia_series('STEO.BREPUUS.M')
```

This is the error that I get

```
Request failed [404]. Retrying in 1.9 seconds...
Request failed [404]. Retrying in 1 seconds...
Error: Page not found
```

**Comment by singh96aman** [comment]
Hi! I am still facing issue with the same. Could you please help asap ?

Code to Reproduce -
library(eia)
eia_set_key("u4h5BwFnv3r8a498z9JYa3DbeggLSDIhBcoZbSEd")
id <- "ELEC.GEN.ALL-AK-99.A"
(d <- eia_series(id, n = 10))

**Comment by rlsweeney** [comment]
I am getting the same error message. Has anyone identified a fix?

**Comment by singh96aman** [comment]
I think it's still making v1 requests so it's not working correctly. 
Closest Solution I found was using eia1_series from https://github.com/jameelalsalam/eia2

**Comment by leonawicz** [comment]
See issue #13
