### ISSUE TITLE
freq = 'weekly'

### ISSUE THREAD

**Issue by era127** [leonawicz/eia#16]
I noticed that the 'weekly' frequency is not supported.  I was wondering if that was left out accidentally or for a particular reason.

```r
.freq_specs <- function(freq){
  if (!is.character(freq) \| length(freq) > 1)
    stop("'freq' must be one of: 'annual', 'yearly', 'monthly', 'daily', or 'hourly'.")
  paste0("&frequency=", freq)
}
```

**Comment by mghoff** [comment]
Thanks for noticing. This was left out by accident and is now available in the `dev` branch of this repo. It will be included in the next release.

**Comment by era127** [comment]
OK thanks
