### ISSUE TITLE
eia_data not returning values for international directory

### ISSUE THREAD

**Issue by morrisseyj** [leonawicz/eia#19]
I am trying to pull international data and getting responses with no value variable. Example code is below:

```
eia_set_key("safekey")

eia_data(dir = "international",
         freq = "annual", 
         start = "2017" ,
         facets = list(activityId = 12, 
                       productId = c(2)))
```

returns the following variables: 
```
"period" 
"productId"
"productName"
"activityId"
"activityName"
"countryRegionId"
"countryRegionName"
"countryRegionTypeId"
"countryRegionTypeName"
"dataFlagId"
"dataFlagDescription"
"unitName"
"unit"
```

There is no value returned - i see the value key in the json if i call that online. What am I missing?

**Comment by leonawicz** [comment]
Do you mean to do the following?

1. Check metadata for the `dir = "international"` to find the value ID.

```
eia_metadata("international")

# output includes:
$Data
# A tibble: 1 × 1
  value.id
  <chr>   
1 value 
```

2. Specify the data ID when calling `eia_data()` in this case.

```
eia_data(
  dir = "international",
  data = "value",
  freq = "annual", 
  start = "2017" ,
  facets = list(activityId = 12, productId = c(2))
)
```

The result now includes the `value` column with numeric values.

**Comment by morrisseyj** [comment]
Thanks, that is what i wanted. 

I was reading the docs here: https://cran.r-project.org/web/packages/eia/eia.pdf. I see now that the data parameter does get called in the example, but it wasn't clear to me from the entry on eia_data that this is how the call would work.

Apologies for the confusion and thanks for the help.

**Comment by leonawicz** [comment]
Sounds good, no problem. I agree we can improve the documentation in this regard.
