### ISSUE TITLE
Data available for download that is not available in API

### ISSUE THREAD

**Issue by leonawicz** [leonawicz/eia#2]
Related to #1 this issue seeks feedback from users about data commonly accessed from the EIA website, but which may not be available through the API itself. I am interested in creating additional wrapper functions for pulling specific, popular datasets from EIA into R that may need to be done by downloading files from specific URLs because they are not available through the API. Please let me know of possible examples and I will keep them in mind.

**Comment by leungi** [comment]
Glad you have this opened 😃 

I can't seem to find a category in `eia_cats()` that group production by _region_ as defined in this [report](https://www.eia.gov/petroleum/drilling/#tabs-summary-2).

It'll be useful given the spotlight on Permian basin.

**Comment by leonawicz** [comment]
It is straightforward enough for me to add a function that downloads and parses xlsx files like the one for this report into a nice table or set of tables.

Do you have additional reports to suggest that are commonly used? It would be helpful for me to see more examples so I can see how diverse the data structures are. It will help me figure out how reasonable it would be for me to make functions for different reports, for example, `report_drilling_productivity()`, `report_a()`, `report_b()`... and so on. And possibly a wrapper function `eia_report()` that can simply be used like `eia_report(id = "drilling productivity")` etc.

I looked at this report and it is very easy (assuming of course, that they do not restructure their file contents or change the url over time and break the code). But it would be good to know if other key reports are similarly easy to handle. I'm not familiar enough in the long term yet to know if their file formats randomly change from time to time. My only hesitancy here is in wanting to hear from more people on how dependable such functions would be. If the EIA randomly adds Excel sheets to a report, changes names, adds additional spacer rows to a table, etc., it would break such a function. That's the downside to these data not being in the API, so I have to be careful before moving too far forward too fast.

The package is currently in software peer review at the moment so for that reason I will also wait a bit before making more updates.

**Comment by leungi** [comment]
Commercial data provider such as Woodmac and Genscape do provide these data (parsed from EIA .xls) in consistent formats in my past experience.

I hope this is due to raw data format being consistent and not because these vendors have a dedicated data cleaning crew 😄

**Comment by leonawicz** [comment]
The latest version contains the example function above as a starting point. See `eia_report()` documentation.

**Comment by leonawicz** [comment]
So far my conclusion is that formatting can and does change in ways that will lead to highly frustrating maintenance issues. So I'm going to close this issue. Going forward I'll consider case by base suggestions where there is some historical evidence suggesting reliably unchanging formatting over time (but I'm not getting my hopes up). It makes sense to stick to the API.

**Comment by leungi** [comment]
Appreciate the accommodation to begin with 🙏

I agree that for these data, the trade-off between maintenance and ease of ad-hoc data download is not worth it.
