### ISSUE TITLE
Feature Request: Parameter/variable to enable https

### ISSUE THREAD

**Issue by mtkerbeR** [leonawicz/eia#6]
First of all: thanks for the great work. The package makes it really comfortable to get data from EIA.

Just a minor point/feature request:
Data from EIA are also available via https. As I prefer this way, I currently achieve this by changing the last line of function eia:::.eia_url manually from "http://api.eia.gov/" to "https://api.eia.gov/"

However, it could probably be useful (also for other users) if "https" could be parameterized in some way (e.g. as a variable or a function argument).

If this is a feature you would consider to implement, I would be happy to provide a pull request.

**Comment by leonawicz** [comment]
Hi, thanks for bringing this to my attention. We've decided to just make it https. You can try now with the latest from GitHub. I'm glad to hear the package has been useful for you.
